### ISSUE TITLE
Element Cleanup: Box

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#625] opened 2017-04-27 19:49 UTC
## Description
As a Box element user, I want to see documentation specific to the Box element for:

* Authentication
* Events and Transform Data
* Endpoint setup
* Create instance
* Bulk
* Error code
* Querying

**Comment by davewilks** [comment] 2017-07-28 16:16
Duplicate of Docathon issues

**Closed by davewilks** 2017-07-28 16:16 UTC
Labels: elements
