### ISSUE TITLE
Element Tips: Dropbox/Box

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#455] opened 2017-03-03 16:27 UTC
## Description
As a Dropbox/Box element user, I want to see specific detailed documentation so that I can implement a new instance with minimal input from Cloud Elements support.

**Comment by KelseyStevenson** [comment] 2017-06-06 19:33
This story is on hold as we observe the changes that were made to DropBox and DropBox business. Content to be added is:
Deleting a file in DropBox will not permanently delete the file. To permanently delete a file, you should use the empty cache flag. 
If you create a new file with the same ID as a "deleted" file, and you have not emptied the cache, DropBox events will return 'Updated' when the file is recreated. To recieve an event type of 'Created' with the same ID as a 'deleted' file, you must permanenetly delete the old file either via the Dropbox UI or the empty cache flag.

If you want to execute a call on behalf of the user and if you have administrator permissions, you can pass in header 'as-user' with the associated user ID.

Business:
Dropbox business controls permissions via the OAuth Application. You can create an OAuth Application to manage File and Folder access.
Events are cursor based for Dropbox business so the actual changes must be queryed.
If you want to execute a call on behalf of the user and if you have administrator permissions, you can pass in header 'as-user' with the associated user ID.
If you are adding `/users`, you must have sufficient licenses to support the additional members as you may be restricted by licensing.

**Comment by davewilks** [comment] 2017-07-28 15:04
Duplicate of Docathon work. Add info from here to #828

**Closed by davewilks** 2017-07-28 15:04 UTC
Labels: elements, quick wins
