### ISSUE TITLE
Element Cleanup: Zendesk

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#623] opened 2017-04-27 19:47 UTC
## Description
As a Zendesk element user, I want to see documentation specific to the Zendesk element for:

* Authentication
* Events and Transform Data
* Endpoint setup
* Create instance
* Bulk
* Error code
* Querying

**Comment by davewilks** [comment] 2017-07-28 16:15
Duplicate of Docathon, most issues closed except CEQL

**Closed by davewilks** 2017-07-28 16:15 UTC
Labels: elements
