### ISSUE TITLE
Show supported versions for QB

### ISSUE THREAD

**Issue by greglindahl** [cloud-elements/devportal#230] opened 2016-11-07 20:30 UTC
## Description
Request from Sales:
Can you add the supported version for G2C for quickbooks to the FAQ doc?
https://developer-static.intuit.com/qbsdk-current/doc/pdf/releasenotes.pdf
versions can be found on page 13

## Acceptance

 add the supported version for G2C for quickbooks to the FAQ doc

**Comment by chaaz** [comment] 2016-11-15 15:25
This is a duplicate of https://github.com/cloud-elements/petit/issues/51, and was fixed in https://github.com/cloud-elements/devportal/commit/fc5a1912d4accc236bc64dc8284de8236d1da6ea

**Closed by chaaz** 2016-11-15 15:25 UTC
Labels: elements, feature
