### ISSUE TITLE
Sage One V3 Documentation

### ISSUE THREAD

**Issue by tclarkCO** [cloud-elements/devportal#695] opened 2017-05-22 16:39 UTC
## Description
* Users will need access to new Sage One V3 (`sageone`) specific documentation
* In this effort `devportal` should hide Sage One US, Sage One UK,  & Sage Live 

**This is a high priority item**

**Comment by tclarkCO** [comment] 2017-05-22 16:39
@tyler-cloud-elements @Tmay14 - Can you guys verify the info above is correct and/or provide any additional info?

**Comment by davewilks** [comment] 2017-05-22 16:43
This looks like a duplicate of #680 and #684. I'm closing it unless you have any objections.

**Comment by Tmay14** [comment] 2017-05-22 16:52
None from me

**Closed** 2017-05-22 16:56 UTC
