### ISSUE TITLE
Hubspot: Polling and Webhooks

### ISSUE THREAD

**Issue by cassiedbrown** [cloud-elements/devportal#316] opened 2017-02-06 18:06 UTC
## Description
Hubspot needs more specific documentation on how to turn on webhooks and use webhooks, as well as more specific documentation for polling.

**Comment by davewilks** [comment] 2017-07-28 15:01
Duplicate of Docathon work - Marketing is done CRM is not yet

**Closed by davewilks** 2017-07-28 15:01 UTC
Labels: elements, quick wins
