### ISSUE TITLE
Salesforce  Webhook Documentation

### ISSUE THREAD

**Issue by cassiedbrown** [cloud-elements/devportal#568] opened 2017-04-17 13:50 UTC
## Description
Currently, the webhook documentation is incorrect and shows that you should set up your Remote Site Settings in Salesforce to include https://api.cloud-elements.com. However, for production it may also need to be https://console.cloud-elements.com

Also, if you are already updating your documentation, I noticed that the security verification was incorrect for the javascript version of the handling for the notification signature key. Just needed to throw a base64 encoding in there on the hex string. Might help out some people in the future!

// https://developers.cloud-elements.com/docs/guides/event-management/security.html 
var key = sjcl.codec.utf8String.toBits(notification_signature_key); 
var out = (new sjcl.misc.hmac(key, sjcl.hash.sha256)).mac(JSON.stringify(req.body)); 
var hex = sjcl.codec.hex.fromBits(out); 
var hmac = new Buffer(hex, 'hex').toString('base64’); // this line needs to be added :) 
// shaHeader == “sha256=“ + hmac 
Again, thanks for your help, and I think we can close this issue.

**Comment by daniel-cherry** [comment] 2017-04-17 14:40
this is a duplicate of #555. I will add the above details to that user story and close this as a duplicate

**Closed** 2017-04-17 14:41 UTC
Labels: elements, quick wins
