### ISSUE TITLE
Element Cleanup: QuickBooks Desktop

### ISSUE THREAD

**Issue by daniel-cherry** [cloud-elements/devportal#620] opened 2017-04-27 19:43 UTC
## Description
As a QuickBooks Desktop element user, I want to see documentation specific to the QuickBooks Desktop element for:

* Authentication
* Events and Transform Data
* Endpoint setup
* Create instance
* Bulk
* Error code
* Querying

**Comment by davewilks** [comment] 2017-07-28 16:14
Duplicate of Docathon items, most of which are closed now.

**Closed by davewilks** 2017-07-28 16:14 UTC
Labels: elements
